export class UpdateSanctionedDto {
//   firstName? :  String
//   middleName? : string
//   lastName? : string
//   title? : string
//   type? : string
//   remark? : string 
//   gender? : string
//   designation? : string
//   motive? : string
//   reference? : string
//   referenceUe? : string
//   referenceOnu? : string
//   unListType? : string
//   listedOn? : string
//   listType? : string
//   submittedBy? : string
//   originalName? : string
//   otherNames? : string[]
}
